---
title: David Cseh | Games and Assets
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: true
    share: true
    related: true
- scope:
    path: _pages
    type: pages
  values:
    layout: single
    author_profile: true
email: info@davidcseh.com
description: David Cseh's personal website serving as a hub for assets and games created
  by myself.
twitter_username: david_cs
github_username: phonebox
minimal_mistakes_skin: air
search: true
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: "/:categories/:title/"
paginate: 5
paginate_path: "/page:num/"
include:
- _pages
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-include-cache
author:
  name: David Cseh
  avatar: "/assets/images/bio-photo.jpg"
  bio: Creating games and photo based materials with Unity
  links:
  - label: Website
    icon: fas fa-fw fa-link
    url: https://davidcseh.com
  - label: Twitter
    icon: fab fa-fw fa-twitter-square
    url: https://twitter.com/davidcs37809381
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/Phonebox/
  - label: Asset store
    icon: fas fab fa-unity
    url: https://assetstore.unity.com/
footer:
  links:
  - label: Twitter
    icon: fab fa-fw fa-twitter-square
    url: https://twitter.com/davidcs37809381
  - label: GitHub
    icon: fab fa-fw fa-github
    url: https://github.com/Phonebox/
  - label: Asset store
    icon: fas fab fa-unity
    url: https://assetstore.unity.com/
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
